version: "3.8"

networks:
  hexagonal-architecture-notes-app:
    external: true

services:
  mysqldb:
    image: mysql:8.0.32
    volumes:
      - ./hexagonal-architecture-notes-app-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root
    restart: on-failure
    networks:
      - hexagonal-architecture-notes-app

  app:
    image: spring-boot-docker:spring-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/notes?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - hexagonal-architecture-notes-app