version: "3.8"

services:
  springboot-app:
    image: spring-boot-docker:spring-docker
    restart: always
    build: .
    ports:
      - 9090:9090
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.32
    ports:
      - 3307:3306
    volumes:
      - ./hexagonal-architecture-notes-app-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
    restart: on-failure